config/routes.rb
Restaurantly::Application.routes.draw do
  resources :restaurants
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root to: "restaurants#index"
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	validates_presence_of :uid
	validates_uniqueness_of :uid

	belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :authorizations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant
      render :show
    else
      flash[:warning] = "sorry that restaurant doesn't exist"
      redirect_to root_path
    end
  end

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    name = params[:restaurant][:name] if params[:restaurant]
    @restaurant = Restaurant.new name: name
    if @restaurant.save
      flash[:success] = "#{@restaurant.name} created"
      redirect_to restaurant_path @restaurant
    else
      flash[:warning] = @restaurant.errors.inspect
      redirect_to new_restaurant_path
    end
  end

  def edit
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant
      render :edit
    else
      redirect_to root_path
    end
  end

  def update
    @restaurant = Restaurant.find_by_id params[:id]
    if @restaurant
      @restaurant.update_attributes(name: params[:restaurant][:name])
      flash[:success] = "name Updated!"
      redirect_to restaurant_path @restaurant
    else
      flash[:alert] = "Houston, we have a problem"
      redirect_to root_path
    end
  end

  def destroy
    @restaurant = Restaurant.find_by_id params[:id]
    @restaurant.destroy
    redirect_to root_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# props to @auser
# the below is mangled a bit from https://leanpub.com/angularjs-rails

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    auth_hash = request.env["omniauth.auth"]
    uid = auth_hash["uid"]
    name = auth_hash["info"]["name"]
    handle = auth_hash["info"]["nickname"]
    auth = Authorization.find_by_provider_and_uid("twitter", uid)

    if auth
      user = auth.user
    else

      unless current_user
        unless user = User.find_by_name(name)
          user = User.create name: name, password: Devise.friendly_token[0,8],
            email: "default@mail.com"#, twitter: handle
        end
      else
        user = current_user
      end
      unless auth = user.authorizations.find_by_provider("twitter")
        auth = user.authorizations.build provider: "twitter", uid: uid
        user.authorizations << auth
      end

      auth.update_attributes uid: uid, token: auth_hash['credentials']['token'],
        secret: auth_hash["credentials"]['secret'], name: name, url: "https://twitter.com/#{name}"
    end

    if user
      sign_in_and_redirect user, :event => :authentication
    else
      redirect_to :new_user_registration
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_sign_in.haml
.row
  .large-2.columns.text-right
    - unless current_user
      = link_to "Sign Up/In", "/users/auth/twitter", class: "button small radius"
    - else
      = link_to "logout", destroy_user_session_path, method: "DELETE"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= render "layouts/sign_in" %>
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/restaurants/create.html.haml
%h1 Restaurants#create
%p Find me in app/views/restaurants/create.html.haml

app/views/restaurants/destroy.html.haml
%h1 Restaurants#destroy
%p Find me in app/views/restaurants/destroy.html.haml

app/views/restaurants/edit.html.haml
.row
  .large-8.columns.large-centered
    %h3.subheader.center
      %b Edit Restaurantly Spot!

%br

.row
  .large-8.columns.large-centered
    = form_for @restaurant do |restaurant|
      = restaurant.text_field :name
      %center
        = restaurant.submit "update", class: "button"
        %br= link_to "back", restaurants_path

app/views/restaurants/index.html.haml
.row
  .large-8.columns.large-centered
    %h3.subheader.center
      %b Restaurantly Spots!

.row
  .large-8.columns.large-centered
    %h5.subheader.center
      = link_to "new", new_restaurant_path

.row
  %br
  .large-8.columns.large-centered
    - @restaurants.each do |restaurant|
      %h5.subheader.center
        = restaurant.name
        (
        %i= link_to "edit", edit_restaurant_path(restaurant)
        |
        %i= link_to "destroy", restaurant_path(restaurant), method: :delete
        )

app/views/restaurants/new.html.haml
.row
  .large-8.columns.large-centered
    %h3.subheader.center
      %b New Restaurantly Spot!

%br

.row
  .large-8.columns.large-centered
    = form_for @restaurant do |restaurant|
      = restaurant.text_field :name, placeholder: "enter name. e.g. 'Mc Ruby on Rails'"
      %center
        = restaurant.submit "submit!", class: "button"
        %br= link_to "back", restaurants_path

app/views/restaurants/show.html.haml
.row
  .large-8.columns.large-centered
    %h1
      %center
        %i= @restaurant.name
    = @restaurant.inspect
    .center
      %p= link_to "return to index", restaurants_path

app/views/restaurants/update.html.haml
%h1 Restaurants#update
%p Find me in app/views/restaurants/update.html.haml